version: '3.8'

services:
  api:
    build: .
    container_name: task_management_api
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-tu_clave_secreta}
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped